platform: Any CPU
configuration: Release
shallow_clone: true
version: 6.0.0.{build}

matrix:
  fast_finish: true

# enable AssemblyInfo.cs patching with build version number
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# restore NuGet packages before running MSBuild
before_build:
  - pip install -U sphinx
  - nuget restore Maestro\Maestro_All.sln

environment:
  COVERALLS_REPO_TOKEN:
    secure: brg0Fy+w8aO/4JhYrsjvumIqAMCi26QNT3nJGUQNaKvLXSoXgywWn/WPCEnUJEEK

build:
  verbosity: minimal
  parallel: true
  project: Maestro\Maestro_All.sln

after_build:
  - if not exist %APPVEYOR_BUILD_FOLDER%\artifacts mkdir %APPVEYOR_BUILD_FOLDER%\artifacts
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\Thirdparty\NSIS
  - cd /D %APPVEYOR_BUILD_FOLDER%\Doc
  - msbuild /p:Configuration=%CONFIGURATION% /v:q
  - move %APPVEYOR_BUILD_FOLDER%\Doc\Help\MaestroAPI.chm %APPVEYOR_BUILD_FOLDER%\SDK\
  - cd /D %APPVEYOR_BUILD_FOLDER%\UserDoc
  - call make.bat html
  - cd /D %APPVEYOR_BUILD_FOLDER%\UserDoc\build\html
  - xcopy /S /Y *.* %APPVEYOR_BUILD_FOLDER%\out\%CONFIGURATION%\UserDoc\
  - cd /D %APPVEYOR_BUILD_FOLDER%\Install
  - makensis.exe /DSLN_CONFIG=%CONFIGURATION% /DCPU=x86 /DRELEASE_VERSION=%APPVEYOR_BUILD_VERSION% Maestro.nsi
  - cd /D %APPVEYOR_BUILD_FOLDER%\SDK
  - 7z a %APPVEYOR_BUILD_FOLDER%\artifacts\Maestro-SDK-%APPVEYOR_BUILD_VERSION%.zip *
  - cd %APPVEYOR_BUILD_FOLDER%

test_script:
- ps: >-
    .\Maestro\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -filter:"+[OSGeo.*]* -[*.tests]* -[*.Tests]* -[Irony]*" -register:user -target:"Maestro\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"OSGeo.MapGuide.MaestroAPI.Tests\bin\Release\OSGeo.MapGuide.MaestroAPI.Tests.dll OSGeo.MapGuide.ObjectModel.Tests\bin\Release\OSGeo.MapGuide.ObjectModels.Tests.dll" -output:OpenCoverCoverage.xml
    
    $coveralls = (Resolve-Path "Maestro/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    & $coveralls --opencover -i OpenCoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID