platform: Any CPU
configuration: Release
shallow_clone: true
version: 6.0.0.{build}
image: Visual Studio 2017

matrix:
  fast_finish: true

# enable AssemblyInfo.cs patching with build version number
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# restore NuGet packages before running MSBuild
before_build:
  - echo CD                             %CD%
  - echo APPVEYOR_PROJECT_NAME          %APPVEYOR_PROJECT_NAME%
  - echo APPVEYOR_PROJECT_SLUG          %APPVEYOR_PROJECT_SLUG%
  - echo APPVEYOR_BUILD_FOLDER          %APPVEYOR_BUILD_FOLDER%
  - echo APPVEYOR_BUILD_ID              %APPVEYOR_BUILD_ID%
  - echo APPVEYOR_BUILD_NUMBER          %APPVEYOR_BUILD_NUMBER%
  - echo APPVEYOR_BUILD_VERSION         %APPVEYOR_BUILD_VERSION%
  - echo APPVEYOR_JOB_ID                %APPVEYOR_JOB_ID%
  - echo APPVEYOR_JOB_NAME              %APPVEYOR_JOB_NAME%
  - echo APPVEYOR_JOB_NUMBER            %APPVEYOR_JOB_NUMBER%
  - echo APPVEYOR_REPO_NAME             %APPVEYOR_REPO_NAME%
  - echo APPVEYOR_REPO_BRANCH           %APPVEYOR_REPO_BRANCH%
  - echo APPVEYOR_REPO_TAG              %APPVEYOR_REPO_TAG%
  - echo APPVEYOR_REPO_TAG_NAME         %APPVEYOR_REPO_TAG_NAME%
  - echo APPVEYOR_REPO_COMMIT           %APPVEYOR_REPO_COMMIT%
  - echo APPVEYOR_REPO_COMMIT_TIMESTAMP %APPVEYOR_REPO_COMMIT_TIMESTAMP%
  - nuget update -self
  - nuget restore Maestro.sln
  - cinst -y docfx

environment:
  COVERALLS_REPO_TOKEN:
    secure: brg0Fy+w8aO/4JhYrsjvumIqAMCi26QNT3nJGUQNaKvLXSoXgywWn/WPCEnUJEEK

build:
  verbosity: minimal
  parallel: true
  project: Maestro.sln

after_build:
  - set ARTIFACT_RELEASE_LABEL=%APPVEYOR_BUILD_VERSION%
  - if "%APPVEYOR_REPO_TAG%" == "true" set ARTIFACT_RELEASE_LABEL=%APPVEYOR_REPO_TAG_NAME%
  - if not exist %APPVEYOR_BUILD_FOLDER%\artifacts mkdir %APPVEYOR_BUILD_FOLDER%\artifacts
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\Packages\nsis\2.51.0\tools
  - cd /D %APPVEYOR_BUILD_FOLDER%\Docs
  - docfx build
  - cd /D %APPVEYOR_BUILD_FOLDER%\out\Release
  - 7z a -mx9 %APPVEYOR_BUILD_FOLDER%\artifacts\MapGuideMaestro-%CONFIGURATION%-%ARTIFACT_RELEASE_LABEL%.zip * -x!LocalConfigure.* -x!Addins\Local -x!Addins\Scripting
  - cd /D %APPVEYOR_BUILD_FOLDER%\MgTileSeeder
  - dotnet publish -c release -f netcoreapp2.0 -r win-x64 -o publish_win
  - dotnet publish -c release -f netcoreapp2.0 -r linux-x64 -o publish_linux
  - cd /D %APPVEYOR_BUILD_FOLDER%\MgTileSeeder\publish_win
  - 7z a -mx9 %APPVEYOR_BUILD_FOLDER%\artifacts\MgTileSeeder-win-x64-%ARTIFACT_RELEASE_LABEL%.zip *
  - cd /D %APPVEYOR_BUILD_FOLDER%\MgTileSeeder\publish_linux
  - 7z a -mx9 %APPVEYOR_BUILD_FOLDER%\artifacts\MgTileSeeder-linux-x64-%ARTIFACT_RELEASE_LABEL%.zip *
  - cd /D %APPVEYOR_BUILD_FOLDER%\Install
  - appveyor DownloadFile https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe
  - makensis.exe /DSLN_CONFIG=%CONFIGURATION% /DCPU=x86 /DRELEASE_VERSION=%ARTIFACT_RELEASE_LABEL% Maestro.nsi
  - cd %APPVEYOR_BUILD_FOLDER%
  - dotnet pack Core.sln --configuration %CONFIGURATION% --output %APPVEYOR_BUILD_FOLDER%\artifacts --include-symbols /p:Version=6.0.0-pre%APPVEYOR_BUILD_NUMBER%"

test_script:
- ps: >-
    .\Packages\opencover\4.6.519\tools\OpenCover.Console.exe -filter:"+[OSGeo.*]* -[*.tests]* -[*.Tests]* -[Irony]*" -register:user -target:".\Packages\xunit.runner.console\2.3.1\tools\net452\xunit.console.exe" -targetargs:"OSGeo.MapGuide.MaestroAPI.Tests\bin\Release\net461\OSGeo.MapGuide.MaestroAPI.Tests.dll OSGeo.MapGuide.ObjectModels.Tests\bin\Release\net461\OSGeo.MapGuide.ObjectModels.Tests.dll -noshadow -xml .\TestResult.xml" -output:OpenCoverCoverage.xml -coverbytest:*.Tests.dll

    $coveralls = (Resolve-Path "Packages/coveralls.net/0.412.0/tools/csmacnz.coveralls.exe").ToString()

    & $coveralls --opencover -i OpenCoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\TestResult.xml))

artifacts:
  - path: .\artifacts\MapGuideMaestro-$(configuration)-$(ARTIFACT_RELEASE_LABEL)-Setup.exe
    name: installer_windows
  - path: .\artifacts\MapGuideMaestro-$(configuration)-$(ARTIFACT_RELEASE_LABEL).zip
    name: portable_package
  - path: .\artifacts\MgTileSeeder-win-x64-$(ARTIFACT_RELEASE_LABEL).zip
    name: seeder_windows
  - path: .\artifacts\MgTileSeeder-linux-x64-$(ARTIFACT_RELEASE_LABEL).zip
    name: seeder_linux
  - path: .\artifacts\*.nupkg
    name: nuget_packages
    type: NuGetPackage

#  - path: .\artifacts\Maestro-SDK-$(ARTIFACT_RELEASE_LABEL).zip
#    name: sdk
#    type: zip

deploy:
  - provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: RZrLa/jeWJt/bpCN57l82c8+1r/I/3XKk92ZL6a7jafsM+3k26IUOEoa6VnYtB0v
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: 'Release $(appveyor_repo_tag_name) ($(appveyor_build_version))'
    auth_token:
      secure: d+aY+YJPCp6KzWE2XcGKdp5XFXoh66H7le3SJiqxtAHDZ1P2+kw/PgIF5Unj3kxG
  #  artifact: installer_windows,sdk
    artifact: installer_windows,portable_package,nuget_packages,seeder_windows,seeder_linux
    draft: true
    prerelease: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only